[tool.poetry]
name = "lnbits-pip-setup"
version = "0.0.0"
description = ""
authors = ["dni <office@dnilabs.com>"]

[tool.poetry.dependencies]
python = "^3.10"
lnbits = "^0.10.3.dev1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
